export default [
//   { name: 'meme1', pic: '../stickers/meme1.png' },
//   { name: 'meme2', pic: '../stickers/meme2.png' },
//   { name: 'meme3', pic: '../stickers/meme3.png' },
//   { name: 'meme4', pic: '../stickers/meme4.png' },
//   { name: 'meme5', pic: '../stickers/meme5.png' },
//   { name: 'meme6', pic: '../stickers/meme6.png' },
//   { name: 'meme7', pic: '../stickers/meme7.png' },
//   { name: 'meme8', pic: '../stickers/meme8.png' },
//   { name: 'meme9', pic: '../stickers/meme9.png' },
//   { name: 'meme10', pic: '../stickers/meme10.png' },
//   { name: 'meme11', pic: '../stickers/meme11.png' },
//   { name: 'meme12', pic: '../stickers/meme12.png' },
//   { name: 'meme13', pic: '../stickers/meme13.png' }
  { name: 'meme1', pic: '/stickers/meme1.png' },
  { name: 'meme2', pic: '/stickers/meme2.png' },
  { name: 'meme3', pic: '/stickers/meme3.png' },
  { name: 'meme4', pic: '/stickers/meme4.png' },
  { name: 'meme5', pic: '/stickers/meme5.png' },
  { name: 'meme6', pic: '/stickers/meme6.png' },
  { name: 'meme7', pic: '/stickers/meme7.png' },
  { name: 'meme8', pic: '/stickers/meme8.png' },
  { name: 'meme9', pic: '/stickers/meme9.png' },
  { name: 'meme10', pic: '/stickers/meme10.png' },
  { name: 'meme11', pic: '/stickers/meme11.png' },
  { name: 'meme12', pic: '/stickers/meme12.png' },
  { name: 'meme13', pic: '/stickers/meme13.png' }
]
